apiVersion: v2
name: ifs-cloud
description: A Helm chart for IFS Business System middle-tier services.

type: application
version: 221.1.0
appVersion: 221.1.0

dependencies:
  - name: applicationtemplate
    version: 1.2.6
    repository: "@ifscloud"
  - name: ifsappamm
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsappapplicationsvc
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsappdoc
    version: 1.2.1
    repository: "@ifscloud"
  - name: ifsappiam
    version: 1.2.9
    repository: "@ifscloud"
  - name: ifsappproxy
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifscore
    version: 1.2.11
    repository: "@ifscloud"
  - name: ifsdbinit
    version: 1.2.5
    repository: "@ifscloud"
  - name: ifsappodata
    version: 1.2.1
    repository: "@ifscloud"
  - name: ifsappclient
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsappclientnotification
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsappclientservices
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsappbusmod
    version: 1.2.1
    repository: "@ifscloud"
  - name: ifsapppowerbisvc
    version: 1.2.1
    repository: "@ifscloud"
  - name: ifsappconnect
    version: 1.2.1
    repository: "@ifscloud"
  - name: ifsappnativeodata
    version: 1.2.2
    repository: "@ifscloud"
  - name: ifsappnativeexecutor
    version: 1.2.2
    repository: "@ifscloud"
  - name: ifsappnativenotification
    version: 1.2.2
    repository: "@ifscloud"
  - name: ifsappnativeserver
    version: 1.2.3
    repository: "@ifscloud"
  - name: ifsapprem
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsappreporting
    version: 1.2.1
    repository: "@ifscloud"
  - name: ifsappreportingbr
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsappreportingcr
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsappreportingren
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsapprmpanel
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsappscim
    version: 1.2.0
    repository: "@ifscloud"
  - name: ifsforecast
    version: 1.1.1
    repository: "@ifscloud"
  - name: ifsmaintenixappserver
    version: 1.2.4
    repository: "@ifscloud"
  - name: ifsmaintenixreportserver
    version: 1.1.1
    repository: "@ifscloud"
  - name: ifsfilestorage
    version: 1.2.1
    repository: "@ifscloud"
  - name: ifsappextensibility
    version: 1.2.1
    repository: "@ifscloud"
  - name: ifsappdb
    version: 1.2.5
    repository: "@ifscloud"
  - name: ifsvirusscanner
    version: 1.2.4
    repository: "@ifscloud"
  - name: ifsappsigningservice
    version: 1.2.3
    repository: "@ifscloud"
